[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python bot_hwb.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
type = "PROCESS"
timeout = 300

[[services]]
name = "hwb-discord-bot"
